# Generated by Django 3.0 on 2021-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='numero_casa',
        ),
        migrations.AddField(
            model_name='visitante',
            name='setor_visitado',
            field=models.CharField(default=1, max_length=100, verbose_name='setor a ser visitada'),
            preserve_default=False,
        ),
    ]
